### PR TITLE
Clean up excessive comments on the collaborator issues

### PR DESCRIPTION
**Pull request by hectorsector**
This PR adds some code that should:
1. Go through the regular process of adding the person that triggered the request
1. Figure out how many comments there are in total
1. If there are >15 comments, make a call to `removeExtraComments()`
1. Step through all comments, starting at the oldest, until 14 comments remain.

👀 @brianamarie @crichid @hollenberry @beardofedu @stoe

### CODE REVIEW

**Comment by stoe** [comment]
The script looks :cool:, @hectorsector, but why would we do this in the first place?

Comments are history and should stay, imho.

**Comment by brianamarie** [comment]
@stoe @hectorsector In most cases, I absolutely agree that keeping history is best practice. _But_, it takes so long to scroll to the bottom of these issues to comment. 

Another solution could be to create a new issue for users to comment on, but there are links to the issue within training-kit which wouldn't be as easy to update. 

@hectorsector I'm 👍 for the idea of this script. How can I help test?

**Comment by hectorsector** [comment]
Thanks for bringing that up @stoe. I was actually so excited about this script's possibility that I didn't think about alternatives. Another approach might be to ask folks to tag their own issue with a collaborator label and the close the issue. Shouldn't be too much harder to implement. What do you think about this alternate approach @brianamarie @stoe?

**Comment by beardofedu** [comment]
Issues have a cap of 2,500 comments based on this:
image

Unless we can modify the number of comments an issue can support, we might need these script @stoe 

Side note: @hectorsector had no idea the comment cap was going to be hit and made this script <3

**Comment by brianamarie** [comment]
Oy! I say we merge this script asap then as a very short term solution, then we work on another longer term solution. 

@hectorsector I don't know if they can add labels without first being collaborators, but could we edit the script to add anyone as a collaborator just by creating an issue in the repository?

**Comment by hectorsector** [comment]
Alrighty I'm ok with that @brianamarie. To test it you'd have to spin up the Sinatra server on your machine, send a post request from an issue to the server, and watch it do its thing. Kinda how we did when we were first getting it set up.

**Comment by stoe** [comment]
why not "replace" the comments with the one from @githubteacher

**Comment by hectorsector** [comment]
> why not "replace" the comments with the one from @githubteacher

I'm not sure I understand, @stoe. Do you mean replace the contents of an existing user comment with one from @githubteacher? Wouldn't this result in the same total comments?

**Comment by crichID** [comment]
> could we edit the script to add anyone as a collaborator just by creating an issue in the repository?

@brianamarie this seems like a promising solution! Another option is to do something similar to what several of our Enterprise customers do -- have a separate page where people "request" to be added as collaborators. The up-side of this is that we could also add 1-2 registration questions and maybe grab emails for our email list :wink:

**Comment by stoe** [comment]
@hectorsector what I wanted to say but didn't finish b/c being on my 📱 

1. Comment as @githubteacher that collaborator was added
2. delete original collaborator comment

Additionally
If we do it that way, then deleting "old" comments shouldn't be that big an issue.
Also, we could document that in the OP of that issue.

**Comment by beardofedu** [comment]
@stoe Although this could be a solution, it just postpones the inevitable maxing out the allowed comments on an issue. Even with one of the two comments (initial request / approval comment) being deleted, we will still end up hitting out cap.

**Comment by stoe** [comment]
> lthough this could be a solution, it just postpones the inevitable maxing out the allowed comments on an issue. Even with one of the two comments (initial request / approval comment) being deleted, we will still end up hitting out cap.

No, @beardofedu, b/c  
> If we do it that way, then deleting "old" comments shouldn't be that big an issue.

**Comment by hectorsector** [comment]
> have a separate page where people "request" to be added as collaborators

Since this is used for learning about GitHub, and we've removed issue usage from the *Intro* class, I think it'd be nice to leave it in Issues and am in favor 👍 of the approach @brianamarie suggested.

**Comment by stoe** [comment]
> but could we edit the script to add anyone as a collaborator just by creating an issue in the repository?

So add collaborator when an issue is created and then close the issue to keep the list clean?

**Comment by brianamarie** [comment]
> So add collaborator when an issue is created and then close the issue to keep the list clean?


@stoe We could do it that way. Or we could have that issue be the one they cite in their PR to close once their PR is merged. (Then with a different script we can add the survey link to merged PRs or the issues attached to them!)

**Comment by stoe** [comment]
Change to `basics.rb` for collaborator by issue:

```rb
post '/payload' do
  push = JSON.parse(request.body.read)
  puts "I got some JSON: #{push.inspect}"

  Collaborator.add repo_name: push["repository"]["full_name"].to_s, issue_num: push["issue"]["number"].to_i, user_login: push["issue"]["user"]["login"].to_s
end
```

Changes to `collaborators.rb` for collaborator by issue:

```rb
require 'octokit'

Octokit.auto_paginate = true

class Collaborator
  def self.add(repo_name:, issue_num:, user_login:)
    begin
      # TODO: we might want to add a check if the `user_login` is already a collaborator

      if user_added = client.add_collaborator(repo_name, user_login)
        message = ":tada: @#{user_login} you are now a repository collaborator. :balloon:"

        client.add_comment repo_name, issue_num, message

        puts message
      else
        puts "Failed to add #{user_login} as a collaborator (check: is githubteacher repository owner?)"
      end
    rescue Octokit::NotFound
      abort "[404] - Repository not found:\nIf #{repo_name || "nil"} is correct, are you using the right Auth token?"
    rescue Octokit::UnprocessableEntity
      abort "[422] - Unprocessable Entity:\nAre you trying to add collaborators to an org-level repository?"
    end
  end

  def self.access_token
    ENV['GITHUBTEACHER_TOKEN'] || raise("You need a GitHub Teacher access token")
  end

  def self.client
    @_client ||= Octokit::Client.new :access_token => access_token
  end
end
```

I can add this as a new PR if y'all are :+1: with it.

**Comment by brianamarie** [comment]
> I can add this as a new PR if y'all are 👍 with it.

@stoe 😍 👍 💯

**Comment by brianamarie** [comment]
@hectorsector Does this need testing to 🚢, or just 👍 for the concept? I say go for it but I want to make sure I support you by testing first if necessary.

**Comment by brianamarie** [comment]
Note this may have broken something - collaborators aren't being added to [the other on demand repo](https://github.com/githubschool/on-demand-github-pages/issues/1). I added manually with hubot for a temporary solution.

**Comment by hectorsector** [comment]
Oh no! I'm sorry to hear that @brianamarie. I'd like to look at the logs on Heroku to see if we can figure out what's going on. Where is this deployed?

**Comment by brianamarie** [comment]
> Where is this deployed?

@hectorsector This is deployed under the `training@github.com` account, with credentials in LastPass.

**Pull request merged**
